// packages/backend/src/routes/cspReports.routes.ts
//
// POST /v1/csp-reports — collector for the frontend's
// Content-Security-Policy-Report-Only reports (#161, staticwebapp.config.json
// generated by packages/frontend/vite/cspPlugin.ts). Accepts both shapes a
// browser can send:
//   - the legacy `report-uri` body, Content-Type application/csp-report:
//     { "csp-report": { "blocked-uri": ..., ... } }
//   - the Reporting API body, Content-Type application/reports+json: an
//     array of { type: "csp-violation", body: { blockedURL: ..., ... } }
//     (other report types the browser might batch into the same endpoint
//     group, if any, are ignored rather than rejected).
//
// Each report is logged once, at warn, with a fixed set of useful fields —
// anything else in the report body is dropped. Fields are truncated to a
// sane length so a pathological report cannot blow up log storage, and at
// most MAX_REPORTS_PER_REQUEST are logged from one request for the same
// reason.
//
// The two content types are not `application/json`, so the app-wide
// express.json() in index.ts (default type 'application/json') never touches
// this body: a route-scoped parser below handles exactly these two types,
// with its own (small) size limit. Its errors -- malformed JSON
// (entity.parse.failed) and oversize (entity.too.large) -- are handled by
// the same app-wide error handler every other route relies on
// (middleware/error.middleware.ts, #143): 400 MALFORMED_BODY / 413
// PAYLOAD_TOO_LARGE.

import { Router, Request, Response } from 'express';
import express from 'express';

import { logger } from '../utils/logger';
import { sendProblem } from '../utils/problem';
import packageJson from '../../package.json';

const router = Router();

const LEGACY_CONTENT_TYPE = 'application/csp-report';
const REPORTING_API_CONTENT_TYPE = 'application/reports+json';
const REPORT_CONTENT_TYPES = [LEGACY_CONTENT_TYPE, REPORTING_API_CONTENT_TYPE];

// Small relative to the 10 MB the rest of the API allows (#143), but not
// tiny: a real Reporting API entry runs ~0.8-1 KB, and Chrome batches
// several queued reports into one delivery, so a limit as tight as 16 KB
// would 413 -- and lose -- a batch of as few as ~16 violations. 64 KB leaves
// headroom for that batching while the 20-report cap (MAX_REPORTS_PER_REQUEST,
// below) and each field's 300-char truncation still bound what actually gets
// logged, regardless of how large an accepted body is.
const BODY_SIZE_LIMIT = '64kb';

const MAX_FIELD_LENGTH = 300;
const MAX_REPORTS_PER_REQUEST = 20;

router.use(express.json({ type: REPORT_CONTENT_TYPES, limit: BODY_SIZE_LIMIT }));

/** A string field, cut to MAX_FIELD_LENGTH; anything else (missing, wrong type) is dropped. */
function truncateString(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  return value.length > MAX_FIELD_LENGTH ? `${value.slice(0, MAX_FIELD_LENGTH)}…` : value;
}

/** A number field, passed through as-is; anything else is dropped. */
function asNumber(value: unknown): number | undefined {
  return typeof value === 'number' ? value : undefined;
}

/** The fixed set of fields logged for one report, whichever body shape it came from. */
interface NormalizedReport {
  effectiveDirective?: string;
  violatedDirective?: string;
  blockedUri?: string;
  documentUri?: string;
  sourceFile?: string;
  lineNumber?: number;
  columnNumber?: number;
  disposition?: string;
}

function normalizeLegacyReport(body: unknown): NormalizedReport | null {
  if (typeof body !== 'object' || body === null) return null;
  const report = (body as Record<string, unknown>)['csp-report'];
  if (typeof report !== 'object' || report === null) return null;
  const r = report as Record<string, unknown>;

  return {
    effectiveDirective: truncateString(r['effective-directive']),
    violatedDirective: truncateString(r['violated-directive']),
    blockedUri: truncateString(r['blocked-uri']),
    documentUri: truncateString(r['document-uri']),
    sourceFile: truncateString(r['source-file']),
    lineNumber: asNumber(r['line-number']),
    columnNumber: asNumber(r['column-number']),
    disposition: truncateString(r.disposition),
  };
}

/** One entry of a Reporting API array; entries that are not a CSP violation are ignored (return null). */
function normalizeReportingApiEntry(entry: unknown): NormalizedReport | null {
  if (typeof entry !== 'object' || entry === null) return null;
  const e = entry as Record<string, unknown>;
  if (e.type !== 'csp-violation') return null;
  if (typeof e.body !== 'object' || e.body === null) return null;
  const b = e.body as Record<string, unknown>;

  return {
    effectiveDirective: truncateString(b.effectiveDirective),
    violatedDirective: truncateString(b.violatedDirective),
    blockedUri: truncateString(b.blockedURL),
    documentUri: truncateString(b.documentURL),
    sourceFile: truncateString(b.sourceFile),
    lineNumber: asNumber(b.lineNumber),
    columnNumber: asNumber(b.columnNumber),
    disposition: truncateString(b.disposition),
  };
}

router.post('/', (req: Request, res: Response) => {
  res.set('API-Version', packageJson.version);

  const contentType = (req.get('content-type') || '').split(';')[0].trim();

  if (!REPORT_CONTENT_TYPES.includes(contentType)) {
    sendProblem(res, req, {
      status: 415,
      title: 'Unsupported Media Type',
      detail: `Content-Type must be one of: ${REPORT_CONTENT_TYPES.join(', ')}.`,
    });
    return;
  }

  let reports: NormalizedReport[];

  if (contentType === LEGACY_CONTENT_TYPE) {
    const report = normalizeLegacyReport(req.body);
    if (!report) {
      sendProblem(res, req, {
        status: 400,
        code: 'INVALID_INPUT',
        detail: 'Body is not a legacy CSP report: expected { "csp-report": { ... } }.',
      });
      return;
    }
    reports = [report];
  } else {
    if (!Array.isArray(req.body)) {
      sendProblem(res, req, {
        status: 400,
        code: 'INVALID_INPUT',
        detail: 'Body is not a Reporting API array of reports.',
      });
      return;
    }
    reports = req.body
      .map((entry) => normalizeReportingApiEntry(entry))
      .filter((report): report is NormalizedReport => report !== null);
  }

  for (const report of reports.slice(0, MAX_REPORTS_PER_REQUEST)) {
    logger.warn('[CSP] violation', report);
  }

  res.status(204).end();
});

export default router;
