// packages/frontend/src/data/dsoAuthorities.ts
//
// Typed access to dsoAuthorities.json, generated by
// scripts/generate-dso-authorities.mjs from the open exports of the Dutch
// government organisations register (organisaties.overheid.nl). Regenerate
// with `npm run authorities:generate` from the repo root.

import raw from './dsoAuthorities.json';

export type AuthorityLevel = 'gemeente' | 'provincie' | 'waterschap' | 'rijk';

export interface DsoAuthority {
  level: AuthorityLevel;
  name: string;
  code: string;
  oin: string;
}

export const DSO_AUTHORITIES: readonly DsoAuthority[] = raw.authorities as DsoAuthority[];

// The register's own name always leads with its level's generic word
// ("Gemeente Aalsmeer", "Provincie Zuid-Holland"), which is useless for
// dropdown type-ahead — everything under one level starts with the same
// word. Waterschappen and ministries are the exception: most already carry
// their own distinctive name ("Hoogheemraadschap van Rijnland", "Wetterskip
// Fryslân", "Financiën") rather than a generic "Waterschap …" / "Ministerie
// van …" prefix, so those regexes only strip the prefix where it is
// actually present.
const LEVEL_PREFIXES: Record<AuthorityLevel, RegExp> = {
  gemeente: /^Gemeente\s+/,
  provincie: /^Provincie\s+/,
  waterschap: /^Waterschap\s+/,
  rijk: /^Ministerie van\s+/,
};

/**
 * The one rule for a short, type-ahead-friendly authority name: strip the
 * level's generic prefix when the register's name actually carries it, and
 * leave distinctive names (a "Hoogheemraadschap …", a bare ministry name)
 * untouched. Used for dropdown option labels, the filter placeholder, and
 * authorityLabel() alike, so there is exactly one place this rule lives.
 */
export function shortName(authority: DsoAuthority): string {
  return authority.name.replace(LEVEL_PREFIXES[authority.level], '');
}

// A handful of Dutch names lead with an elided article — "'s-Hertogenbosch"
// ("'s Hertogenbosch", i.e. "des Hertogen bosch") — which would otherwise
// sort ahead of every other letter instead of under "H". Only the leading
// occurrence is stripped for sorting; the displayed name keeps its
// apostrophe.
function sortKey(name: string): string {
  return name.replace(/^('s-|'t |'s )/, '');
}

/** A level's authorities, sorted by their short name (Dutch collation). */
export function authoritiesByLevel(level: AuthorityLevel): DsoAuthority[] {
  return DSO_AUTHORITIES.filter((a) => a.level === level).sort((a, b) =>
    sortKey(shortName(a)).localeCompare(sortKey(shortName(b)), 'nl')
  );
}

export function findAuthorityByOin(oin: string): DsoAuthority | undefined {
  return DSO_AUTHORITIES.find((a) => a.oin === oin);
}
